{"uuid": "98c783df-3ab9-4372-95c0-90b01c072034", "children": ["62d01dec-131c-424d-8296-a410867c5a98"], "befores": [{"name": "random_user", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to register user. Response: {'success': False, 'message': 'User already exists'}\nassert 403 == 200\n +  where 403 = <Response [403]>.status_code\n", "trace": "  File \"C:\\Users\\Leila Magomedova.WKST-QA-08\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Leila Magomedova.WKST-QA-08\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Leila Magomedova.WKST-QA-08\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Leila Magomedova.WKST-QA-08\\PycharmProjects\\Diploma\\Diplom_3\\conftest.py\", line 34, in random_user\n    assert response.status_code == 200, f\"Failed to register user. Response: {response.json()}\"\n"}, "start": 1715533286060, "stop": 1715533286533}], "start": 1715533286060, "stop": 1715533286538}